grooteogi/backend

- README.md
- api/src/main/java/insaengseonbae/InsaengSeonbaeApplication.java
- api/src/main/java/insaengseonbae/controller/UserController.java
- api/src/main/java/insaengseonbae/domain/User.java
- api/src/main/java/insaengseonbae/repository/UserRepository.java
- api/src/main/java/insaengseonbae/service/UserService.java
- api/src/main/resources/application-dev.yml
- docker-compose.dev.yml
Related issues
---
[ISSB-50 implement get user api](https://babiyak.atlassian.net/browse/ISSB-50)
> implement get user api

- README.md
- api/build.gradle
- api/src/main/java/grooteogi/utils/RedisClient.java
- api/src/main/resources/application-dev.yml
- docker-compose.dev.yml
Related Issues
---
[GRTG-138 setting redis](https://babiyak.atlassian.net/browse/GRTG-138)
Changes
---
- Add redis connection
- Add RedisClient to get and set data from redis
- Update README.md
> setting redis

- api/build.gradle
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/domain/Hashtag.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/dto/Response.java
- api/src/main/java/grooteogi/dto/Token.java
- api/src/main/java/grooteogi/dto/UserDto.java
- api/src/main/java/grooteogi/enums/HashtagType.java
- api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
- api/src/main/java/grooteogi/enums/LoginType.java
- api/src/main/java/grooteogi/service/EmailService.java
- api/src/main/java/grooteogi/utils/JwtProvider.java
- api/src/main/resources/application.yml
Changes
---
- Cleanup build.gradle
- Add response dto to define body structure
- Update application.yml to ignore null field in response
- Remove unnecessary annotation in token dto
> refactor: Organize source code structure

- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/dto/response/BasicResponse.java
- api/src/main/java/grooteogi/dto/response/ExceptionResponse.java
- api/src/main/java/grooteogi/exception/ApiException.java
- api/src/main/java/grooteogi/exception/ApiExceptionAdvice.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/UserService.java
- 에러 처리를 Exception을 이용하여 처리하도록 수정
- 예외 관련 클래스 생성
- 유저 컨트롤러 상의 에러 처리를 예외로 변경
- import 오류 수정
> Change error handling to exception

- api/build.gradle
- api/config/google_checks.xml
- api/config/intellij-java-google-style.xml
- api/src/main/java/grooteogi/config/WebSecurityConfig.java
- api/src/main/java/grooteogi/controller/HashtagController.java
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/domain/Hashtag.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/domain/UserHashtag.java
- api/src/main/java/grooteogi/domain/UserInfo.java
- api/src/main/java/grooteogi/dto/EmailCodeRequest.java
- api/src/main/java/grooteogi/dto/EmailRequest.java
- api/src/main/java/grooteogi/dto/LoginDto.java
- api/src/main/java/grooteogi/dto/Token.java
- api/src/main/java/grooteogi/dto/UserDto.java
- api/src/main/java/grooteogi/dto/response/BasicResponse.java
- api/src/main/java/grooteogi/dto/response/ExceptionResponse.java
- api/src/main/java/grooteogi/enums/HashtagType.java
- api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
- api/src/main/java/grooteogi/enums/LoginType.java
- api/src/main/java/grooteogi/exception/ApiException.java
- api/src/main/java/grooteogi/exception/ApiExceptionAdvice.java
- api/src/main/java/grooteogi/repository/UserRepository.java
- api/src/main/java/grooteogi/service/EmailService.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/UserService.java
- api/src/main/java/grooteogi/utils/JwtProvider.java
- api/src/main/java/grooteogi/utils/RedisClient.java
java code linter인 checkstyle을 도입하여 코드를 일관된 스타일로 작성할 수 있게 합니다.
- checkstyle 구글 코드 스타일 적용
- 스타일에 맞게 코드 수정
- 모든 클래스 및 함수에 자바독 필수적으로 작성되어야 함
> setting checkstyle

- api/src/main/java/grooteogi/controller/HashtagController.java
- api/src/main/java/grooteogi/controller/UserHashtagController.java
- api/src/main/java/grooteogi/repository/HashtagRepository.java
- api/src/test/java/grooteogi/ApplicationTests.java
코드 통합과정에서 발생한 에러 수정 및 컨트롤러 리턴 타입 통일화
- fix: Delete invalid import
- refactor: Change to generate response using basic_response
> refactor: Unify controller return type

- api/build.gradle
- api/config/checkstyle/checkstyle.xml
- api/config/checkstyle/suppressions.xml
- api/config/checkstyle/suppressions_1_2.dtd
checkstyle에서 javadoc 오류 예외처리
checkstyle suppressions 파일 추가 및 설정
> Add checkstyle suppresions to ignore javadoc error

- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/UserService.java
- api/src/main/java/grooteogi/utils/JwtProvider.java
Access Token이 만료되었을 경우 Refresh Token을 확인해 Access Token 갱신
- token verify 시 email이 아닌 user의 전체 정보 전달
- /user/verify 에서 만료 시와 오류 시의 error code 분리
- /user/refresh 에서 refresh token을 확인해 access token 갱신
> Grtg 114 refresh token

- api/src/main/java/grooteogi/controller/HashtagController.java
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/controller/UserHashtagController.java
- api/src/main/java/grooteogi/domain/Hashtag.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/domain/UserHashtag.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/repository/HashtagRepository.java
- api/src/main/java/grooteogi/repository/UserHashtagRepository.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
- api/src/main/java/grooteogi/service/UserService.java
- api/src/main/java/grooteogi/utils/JwtProvider.java
코드 스타일 정리
- 체크스타일 컨벤션에 맞게 코드 수정
- 중복을 제거하기 위해 RequestMapping 사용
- 컨트롤러에서 리스트 반환시 count 제공
- 유저 해시태그 레파지토리에서 데이터 가져오는 방식을 메서드로 처리
> cleanup code style

- .github/workflows/ci.yml
Add github actions for ci
- ci.yml 파일 생성
- PR 시 체크 스타일 테스트하도록 설정
> Add ci.yml to test checkstyle

- api/src/main/java/grooteogi/controller/HashtagController.java
- api/src/main/java/grooteogi/controller/UserHashtagController.java
- api/src/main/java/grooteogi/dto/HashtagDto.java
- api/src/main/java/grooteogi/dto/UserHashtagDto.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
Post API 파라미터 수정
Hashtag Dto, User Hashtag Dto 생성하고
Request param -> Request Body로 변경
> fix: Fix Post api Request param to Request Body

- api/src/main/java/grooteogi/service/UserHashtagService.java
잘못된 코드 수정
for문 안에서 hashtagId 배열을 i로 적어야할 것을 0으로 적어서 제대로 수정
> fix: Fix deleteUserHashtag Method

- api/src/main/java/grooteogi/domain/Post.java
- api/src/main/java/grooteogi/domain/PostHashtag.java
POST 관련 DB 구축하기
Post, PostHash 도메인 객체입니다
.
> feat: Create db tables related post

- api/src/main/java/grooteogi/domain/Hashtag.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/repository/HashtagRepository.java
- api/src/main/java/grooteogi/repository/UserHashtagRepository.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
hashtag table에 count column 추가하고 그에 맞게 repository, service 수정
count column 추가, hashtag repository query문 변경, service에서 count 수량 변경
> fix: Add column count in hashtag and setting count

- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/service/EmailService.java
- api/src/main/java/grooteogi/service/UserService.java
refactoring code
이메일 유효성 검사, 이메일 인증코드 생성 및 확인 코드에서의 오류 처리를 Controller -> Service로 이동
간편 로그인은 refactoring 하지 않음
> refactor: Modify exception handling code

- docker-compose.local.yml
Update docker-compose.local.yml to add email env
docker-compose.local에 이메일 설정 적용
이메일 설정 파일 생성 필수
> chore: Update docker-compose.local.yml to add email env

- README.md
- api/.gitignore
- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
- api/src/main/resources/application.yml
- docker-compose.local.yml
Create dev.env for secret environment variables
노출되면 안되는 환경변수 설정을 위해 dev.env 생성
- 더 이상 application-email.yml은 사용하지 않아도 됩니다.
- 대신 [env_file](https://github.com/grooteogi/backend/wiki/env_file) 위키 참고
> Create dev.env for secret environment variables

- api/build.gradle
- api/src/main/java/grooteogi/config/AwsS3Config.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/utils/AmazonS3Client.java
- api/src/main/resources/application-dev.yml
s3에 파일 업로드, 삭제를 위한 S3Client 제작
- utils 폴더에 S3Client 파일 생성
- 환경변수 설정 필요
> Create amazon s3 client 

- api/src/main/java/grooteogi/config/AwsS3Config.java
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/utils/AwsS3Client.java
- api/src/main/resources/application-dev.yml
- api/src/main/resources/application.yml
yml 파일에 있던 S3 Environment를 env로 옮기기 
yml 파일에 있던 S3 Environment를 env로 옮기기
> Set AWS S3 Environment

- api/build.gradle
- api/src/main/java/grooteogi/config/AccessDeniedHandlerConfig.java
- api/src/main/java/grooteogi/config/AuthenticationEntryPointConfig.java
- api/src/main/java/grooteogi/config/WebSecurityConfig.java
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/dto/OAuthDto.java
- api/src/main/java/grooteogi/dto/OauthDto.java
- api/src/main/java/grooteogi/dto/UserDto.java
- api/src/main/java/grooteogi/enums/LoginType.java
- api/src/main/java/grooteogi/service/UserService.java
- api/src/main/java/grooteogi/utils/OauthClient.java
- api/src/main/resources/application.yml
카카오 간편 회원가입/ 로그인을 위한 백엔드 로직
- 클라이언트로부터 받은 token으로 카카오에 사용자 정보 요청
- 해당 정보를 확인해 없는 사용자면 사용자 회원가입 진행
- 최종적으로 User와 Token을 클라이언트에게 전달
- 인증코드 > 토큰 > 정보 조회 의 순서에서 정보 조회만 완료. ( 작업 단위 확인 필요 )
> Get KAKAO User Info using token

- api/src/main/java/grooteogi/domain/Post.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
간단 코드 수정
Post domain 수정(json ignore 삭제), UserHashtag service getUserHashtag method findById -> findByUserId로 수정
> fix: Update post domain & fix get_user_hashtag logic

- api/src/main/java/grooteogi/service/UserService.java
#52 [BUG] 동일한 이메일로 중복 회원가입
이메일 중복 검사
회원가입 시, 이메일 중복 검사 로직 추가
> fix: Add check email duplication

- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
> Feat : Add Exception Handling Code

- api/src/main/java/grooteogi/controller/ProfileController.java
- api/src/main/java/grooteogi/domain/UserInfo.java
- api/src/main/java/grooteogi/dto/ProfileDto.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/repository/UserRepository.java
- api/src/main/java/grooteogi/service/ProfileService.java
- api/src/main/java/grooteogi/utils/Validator.java
[FEAT] 유저 프로필  수정
유저 프로필 가져오기
유저 프로필 수정하기
* 수정 시, 닉네임 중복 확인하기
* 수정 시, 비밀번호 유효성 검사하기
UserInfo 도메인에서 relation 삭제
이미지 수정은 추후 할 예정
> Grtg 200 edit user profile

- api/src/main/java/grooteogi/config/WebConfig.java
- api/src/main/java/grooteogi/config/WebSecurityConfig.java
- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
- api/src/main/resources/application.yml
#56 [REFACTOR] Modify configurations for production
배포환경을 위한 환경설정 변경
refactor: Change aws region & bucket config to env
refactor: Update cors configs to change origin_url
X
> modify configurations for production

- api/src/main/java/grooteogi/config/WebSecurityConfig.java
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/utils/OauthClient.java
- api/src/main/resources/application.yml
> Create google oauth back logic

- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/utils/OauthClient.java
- api/src/main/resources/application.yml
Google API 연동으로 회원가입 및 로그인 구현 완료
> Implement google oauth

- api/src/main/java/grooteogi/service/EmailService.java
- api/src/main/resources/application.yml
[GRTG-221](https://babiyak.atlassian.net/browse/GRTG-221) setting outlook mail server
도메인 이메일로 보내도록 설정
이메일 호스트를 아웃룩으로 변경
helper.setFrom()으로 서버 도메인을 직접 지정 안해주면 에러 발생하니 주의
> Setting outlook mail server

- api/src/main/java/grooteogi/controller/AwsS3Controller.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/AwsS3Service.java
[FEAT] Implement aws s3 api
AWS S3에 이미지 저장, 삭제 구현
- 파일 업로드하여 이미지 저장
- 파일 이름으로 이미지 삭제
- ApiExceptionEnum 에서 INVALID_FILE_FORMAT_EXCEPTION 추가
> feat: Implement aws s3 api

- api/src/main/java/grooteogi/controller/UserHashtagController.java
- api/src/main/java/grooteogi/dto/PostDto.java
- api/src/main/java/grooteogi/dto/UserHashtagDto.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
[HOTFIX] Fix about hashtag
- 해시태그 관련 로직 수정
- UserHashtagDTO, PostDTO에서
(int)hashtagIds -> (String)hashtags
- 관련된 로직도 tag를 통해 조회 가능하도록 수정
- UserHashtagService에서 null 체크 받던 것 삭제
- 기존 for문 / 향상 for문 ->  forEach 문으로 전부 변경
- Request로 받는 User에 대한 NULL 예외처리
- Request로 받는 Hashtags에 대한 유효하지 않은 값 예외처리
Postman으로 테스트 완료!
머지 되면 이후에 복잡한 부분 메소드로 따로 뺄 예정
> fix: Fix about hashtag

- api/src/docs/asciidoc/api.adoc
- api/src/test/java/grooteogi/UserDocumentationTests.java
Grtg 195 user api test code
유저 테스트 코드 작성
- Add user register api test
- Add get all user api test
- Add get user api test
- Add delete user api test
> Implement user api test code

- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/dto/EmailCodeDto.java
- api/src/main/java/grooteogi/dto/EmailDto.java
- api/src/main/java/grooteogi/service/EmailService.java
- api/src/main/java/grooteogi/service/UserService.java
코드 수정
* user password api uri 변경
* user password api exception enum value 변경
* email dto class 이름 변경
> Refactoring

- api/src/main/java/grooteogi/domain/Like.java
- api/src/main/java/grooteogi/domain/Post.java
- api/src/main/java/grooteogi/domain/Reservation.java
- api/src/main/java/grooteogi/domain/Review.java
- api/src/main/java/grooteogi/domain/Schedule.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/enums/CreditType.java
예약관련 도메인 생성
Reservation/Schedule/Review/Like table + CreditType enum class
> feat: Update db tables related reservation

- api/src/main/java/grooteogi/domain/Heart.java
- api/src/main/java/grooteogi/domain/Post.java
- api/src/main/java/grooteogi/domain/User.java
fetch multiple bags 에러 해결
- Post 도메인에 연관관계를 지연 로딩으로 변경
- Like 테이블 네임 -> Heart로 변경
즉시 로딩으로 여러 테이블과 일대다 관계를 맺으면 발생하는 오류인거 같습니다.
> fix fetch multiple bags hibernate error

- api/src/main/java/grooteogi/controller/AuthController.java
[GRTG-232](https://babiyak.atlassian.net/browse/GRTG-232) Oauth API 리팩터링
AuthController와 OauthController 병합 및 oauth 코드 리팩토링
> refactor: Oauth code refactoring

- api/src/main/java/grooteogi/controller/ReservationController.java
- api/src/main/java/grooteogi/domain/Post.java
- api/src/main/java/grooteogi/domain/Reservation.java
- api/src/main/java/grooteogi/domain/Review.java
- api/src/main/java/grooteogi/domain/Schedule.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/dto/PostDto.java
- api/src/main/java/grooteogi/dto/ReservationDto.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/repository/ReservationRepository.java
- api/src/main/java/grooteogi/repository/ScheduleRepository.java
- api/src/main/java/grooteogi/service/AuthService.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/java/grooteogi/service/ReservationService.java
* 도메인 수정
* exception enum value 수정
* 스케쥴 생성 api
* postdto 수정
* 예약 crud api 생성
reservationController의 getUserReservation은 하는 중입니다.
> EDIT domain AND FEAT reservation

- api/src/main/java/grooteogi/controller/ReservationController.java
- api/src/main/java/grooteogi/domain/Reservation.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/dto/ReservationDto.java
- api/src/main/java/grooteogi/dto/ReservationRes.java
- api/src/main/java/grooteogi/mapper/BasicMapper.java
- api/src/main/java/grooteogi/mapper/ReservationMapper.java
- api/src/main/java/grooteogi/repository/ReservationRepository.java
- api/src/main/java/grooteogi/service/ReservationService.java
#81 fix reservation api
예약 조회 로직 수정
예약 생성 로직 수정
Mapper 도입 ( Cross-change between DTO and ENTITY )
mapper 좀 더 알아가는 중입니다.
> FIX reservation api AND ADD mapper

- api/src/main/java/grooteogi/mapper/ReservationMapper.java
ReservationMapper에서 toEntity()에 mapping() 추가
- schedule set 안해줘서 DB에 null로 저장되던 오류였습니다.
> fix: Add reservationMapper mapping annotation

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/dto/PostDto.java
- api/src/main/java/grooteogi/service/PostService.java
PostController에서 PostDto -> PostDto.Request로 변경
Response는 안 만들었어요.
변경 후, 바뀐 코드에 대해 실행 되는 지 모두 테스트 했어요.
> refactor post dto

- api/src/main/java/grooteogi/domain/Hashtag.java
- api/src/main/java/grooteogi/domain/Post.java
- api/src/main/java/grooteogi/domain/PostHashtag.java
- api/src/main/java/grooteogi/domain/Reservation.java
- api/src/main/java/grooteogi/domain/Review.java
- api/src/main/java/grooteogi/domain/User.java
- api/src/main/java/grooteogi/domain/UserHashtag.java
- api/src/main/java/grooteogi/domain/UserInfo.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/java/grooteogi/service/ReservationService.java
- api/src/main/java/grooteogi/service/UserHashtagService.java
- api/src/main/java/grooteogi/service/UserService.java
- api/src/test/java/grooteogi/ReservationDocumentationTests.java
필요없는 타임스탬프 세터 제거
- 타임스탬프 필드명 통일
- 업데이트 타임스탬프 어노테이션 추가
- 서비스 로직에서 타임스탬프 지정하는 코드 삭제
> refactor: Remove unnecessary timestamp setter

- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
[GRTG-260](https://babiyak.atlassian.net/browse/GRTG-260)
local에서는 docker db 연결, dev에서는 RDS와 연결되도록 설정
> feat: Divide environment db

- api/src/main/java/grooteogi/controller/ReviewController.java
- api/src/main/java/grooteogi/domain/Review.java
- api/src/main/java/grooteogi/dto/ReviewDto.java
- api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
- api/src/main/java/grooteogi/mapper/ReviewMapper.java
- api/src/main/java/grooteogi/repository/ReviewRepository.java
- api/src/main/java/grooteogi/service/ReviewService.java
[GRTG-263 리뷰API](https://babiyak.atlassian.net/browse/GRTG-263)
리뷰 API 제작
> feat: Create review API

- .travis.yml
GRTG-279-deploy-project-buildfile-to-s3
travis ci 설정에 S3 배포 설정 추가
> chore: Add deploy s3 configs to .travis.yml

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/resources/static/docs/api.html
- api/src/test/java/grooteogi/PostDocumentationTests.java
포스트 수정 혹은 삭제 시, 유저 권한 확인 로직 추가
> 포스트 수정 혹은 삭제 시, 유저 권한 확인

- .travis.yml
GRTG-279-deploy-project-buildfile-to-s3
s3 버킷 네임 잘못 지정해서 수정했습니다.
> fix: Collect s3 bucket name

- api/src/main/java/grooteogi/controller/ReservationController.java
- api/src/main/java/grooteogi/dto/ReservationDto.java
- api/src/main/java/grooteogi/service/ReservationService.java
refactor: Send sms api
핸드폰 인증 API 리팩터링
send-sms 수정
check-sms 추가
> refactor: Send sms api

- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/HashtagService.java
- api/src/main/java/grooteogi/service/ReservationService.java
- api/src/main/java/grooteogi/service/ReviewService.java
> refactor exception enum

- api/src/main/java/grooteogi/controller/ReservationController.java
- api/src/main/java/grooteogi/repository/ReservationRepository.java
- api/src/main/java/grooteogi/service/ReservationService.java
- api/src/test/java/grooteogi/ReservationDocumentationTests.java
> Grtg 275 reservation user check

- .travis.yml
- appspec.yml
- scripts/deploy.sh
Grtg 281 add codedeploy config
코드 디플로이 설정 추가하여 CI/CD
- appspec.yml 추가하여 코드 디플로이 설정
- deploy.sh 쉘 스크립트 추가
- .travis.yml 설정 변경
> Grtg 281 add codedeploy config

- .travis.yml
Grtg 281 add codedeploy config
- travis 설정 파일 수정
- 배포 스크립트 수정
> chore: Update .travis.yml to fix script

- .travis.yml
GRTG 281 add codedeploy config
travis 설정 파일 업데이트
모든 브랜치에서 코드 디플로이 실행되도록 수정
> chore: Update .travis.yml to allow codedeploy on all branches

- api/src/main/resources/application-dev.yml
GRTG-282 setting redis config
application-dev.yml 업데이트
AWS ElastiCache 연결 설정 추가
> chore: Update application-dev.yml to add redis url

- api/build.gradle
- scripts/deploy.sh
Grtg 283 resolve deploy error
배포 중에 생긴 문제 해결
- deploy.sh 상에서 필요없는 스크립트 제거
- 배포 시 coolsms 패키지가 compileOnly라 발생하는 문제
-  implementation으로 변경하여 해결
> Grtg 283 resolve deploy error

- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
- api/src/main/resources/application.yml
GRTG-283-resolve-deploy-error
origin url 환경변수로 변경
> refactor: Set origin url to env

- api/src/main/resources/application-dev.yml
GRTG-283-resolve-deploy-error
개발 서버 포트 8080 -> 80으로 변경
> chore: Set server port to 80

- api/src/main/java/grooteogi/config/WebConfig.java
- api/src/main/java/grooteogi/controller/AuthController.java
- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/controller/UserController.java
- api/src/main/java/grooteogi/dto/UserDto.java
- api/src/main/java/grooteogi/dto/auth/OauthDto.java
- api/src/main/java/grooteogi/dto/auth/Oauthdto.java
- api/src/main/java/grooteogi/mapper/UserMapper.java
- api/src/main/java/grooteogi/service/AuthService.java
- api/src/main/java/grooteogi/service/UserService.java
- api/src/main/java/grooteogi/utils/OauthClient.java
- api/src/main/resources/static/docs/api.html
- api/src/test/java/grooteogi/AuthDocumentationTests.java
- api/src/test/java/grooteogi/UserDocumentationTests.java
[GRTG-278](https://babiyak.atlassian.net/browse/GRTG-278)
- getUser, getUserAll 과 같은 사용하지 않는 API 삭제
- Map을 이용해 token과 user을 가져오던 코드 수정
> Auth 관련 필요없는 API 삭제, oauth 리팩토링

- api/src/main/java/grooteogi/mapper/PostMapper.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/resources/static/docs/api.html
포스트 생성 시, setter 함수 삭제
포스트 매퍼 toEntity( ) 파라미터 추가
> 포스트 생성 로직 수정 및 매퍼 수정

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/domain/Schedule.java
- api/src/main/java/grooteogi/dto/PostDto.java
- api/src/main/java/grooteogi/enums/RegionType.java
- api/src/main/java/grooteogi/mapper/PostMapper.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/test/java/grooteogi/ApiDocumentUtils.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
- api/src/test/java/grooteogi/ReservationDocumentationTests.java
1. 기존 `search()` param에서 region 조건 추가
2. RegionType enum 생성
3. Schedule 도메인 수정 
4. PostMapper 수정
5. 서비스 로직 변경 시, 테스트 코드 에러 발생. 테스트코드 기본 형식만 유지하고 private 함수는 모두 삭제
> 포스트 검색 시, region 조건 추가 및 RegionType enum 클래스 생성 및 스케쥴 도메인 수정

- api/build.gradle
- api/src/main/resources/application-dev.yml
Grtg 292 fix/resolve env vars injection error on dev server
개발 서버에서 환경변수 주입 안되는 문제 해결
아마존 파라미터 스토어 연동 설정 추가
> Grtg 292 fix/resolve env vars injection error on dev server

- api/src/test/java/grooteogi/AwsS3DocumentationTests.java
- 이미지 업로드
- 이미지 삭제
테스트 코드 작성
아래 링크 참고
https://www.baeldung.com/spring-multipart-post-request-test
https://kukekyakya.tistory.com/549
> AWS S3 컨트롤러 api 테스트

- api/src/test/java/grooteogi/ReviewDocumentationTests.java
- 리뷰 생성
- 리뷰 수정
- 리뷰 삭제
테스트 코드 형식만 작성
> 예약 컨트롤러 api 테스트 코드

- api/src/main/java/grooteogi/controller/AwsS3Controller.java
> AWS 컨트롤러 응답 메세지 추가

- api/src/main/java/grooteogi/controller/HashtagController.java
> 해시태그 컨트롤러 응답 메세지 추가

- api/src/main/java/grooteogi/controller/UserController.java
> 유저 컨트롤러 api 응답 메세지 추가

- api/src/test/java/grooteogi/PostDocumentationTests.java
포스트 컨트롤러 모든 api 테스트 코드 작성
- 기존 api 테스트 코드 수정
- 리펙토링 이후 추가된 api 테스트 코드 작성
> 포스트 컨트롤러 api 테스트

- api/src/test/java/grooteogi/ReservationDocumentationTests.java
예약 컨트롤러 모든 api 테스트 코드 작성
- 기존 코드 리펙토링
- 서비스 로직 리펙토링 이후 새로 정의된 api 테스트 코드 작성
> 예약 컨트롤러 api 테스트

- api/src/docs/asciidoc/api.adoc
- api/src/test/java/grooteogi/AwsS3DocumentationTests.java
이미지 업로드 시, response.data 필드 노출 문제 해결 해야 함
[여기](https://velog.io/@tmdgh0221/Spring-Rest-Docs-%EC%A0%81%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0) 참고했습니다.
> AWS S3 컨트롤러 테스트 코드 문서화

- api/src/main/java/grooteogi/service/PostService.java
포스트 생성 시 유저 체크
- PostService 내 user가 없을 때 예외처리
> refactor: In create post logic, check the user

- api/src/docs/asciidoc/api.adoc
- api/src/test/java/grooteogi/ReviewDocumentationTests.java
> 리뷰 컨트롤러 테스트 코드 문서화

- api/src/main/java/grooteogi/domain/Schedule.java
schedule domain annotation 추가
- string type으로 db에서 정의할 수 있게 어노테이션 추가
- length 10 -> 20으로 수정
> hotfix: Add anotation in Schedule domain

- api/src/docs/asciidoc/api.adoc
- api/src/test/java/grooteogi/UserDocumentationTests.java
> 유저 컨트롤러 테스트코드 문서화

- api/src/main/java/grooteogi/mapper/UserInfoMapper.java
[GRTG-343](https://babiyak.atlassian.net/browse/GRTG-343)
User Profile을 가져올 때 request 가 동일하도록 로직 변경
> User API 변경

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/domain/Reservation.java
- api/src/main/java/grooteogi/enums/ReservationStatus.java
- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/repository/HeartRepository.java
- api/src/main/java/grooteogi/repository/ReservationRepository.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/java/grooteogi/service/ReservationService.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
- api/src/test/java/grooteogi/ReservationDocumentationTests.java
[GRTG-344](https://babiyak.atlassian.net/browse/GRTG-344)
Post 와 Reservation API 를 테스트하며 정해진 DTO와 다르거나 로직이 작동하지 않는 코드들 수정
> Post, Reservation API 변경

- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
테스트 서버에서 모든 호스트 접속 허용하도록 변경
- properties 파일 수정
> 테스트 서버에서 모든 호스트 접속 허용하도록 변경

- api/src/main/java/grooteogi/service/UserService.java
> 세미콜론 오류 해결

- api/src/docs/asciidoc/api.adoc
- api/src/main/java/grooteogi/controller/AuthController.java
- api/src/main/java/grooteogi/service/AuthService.java
- api/src/test/java/grooteogi/AuthDocumentationTests.java
> auth controller 문서화

- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
> 특정 url에서 요청한 요청만 처리하도록 수정

- api/src/test/java/grooteogi/AuthDocumentationTests.java
- api/src/test/java/grooteogi/AwsS3DocumentationTests.java
- api/src/test/java/grooteogi/HashtagDocumentationTests.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
- api/src/test/java/grooteogi/ReservationDocumentationTests.java
- api/src/test/java/grooteogi/ReviewDocumentationTests.java
- api/src/test/java/grooteogi/UserDocumentationTests.java
auth login 오류 해결
post getPost 오류 해결
> 테스트 코드 문서화 최종 확인 및 오류 해결

- api/build.gradle
- api/src/main/java/grooteogi/config/WebConfig.java
- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
개발 서버에서 모든 호스트 요청 허용
- cors origin `*`로 변경
- 필요없는 코드 삭제
- test 코드 빌드 시 실행되도록 수정
> 개발 서버에서 모든 호스트 요청 허용하도록 수정

- api/src/main/java/grooteogi/config/WebSecurityConfig.java
`WebSecurityConfig`가 모든 호스트 접속 가능하도록 수정
> fix: Update web security config to allow all hosts

- api/build.gradle
- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/mapper/PostMapper.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
- api/src/test/java/grooteogi/AwsS3DocumentationTests.java
- api/src/test/java/grooteogi/HashtagDocumentationTests.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
- api/src/test/java/grooteogi/ReviewDocumentationTests.java
- api/src/test/java/grooteogi/UserDocumentationTests.java
[GRTG-374](https://babiyak.atlassian.net/browse/GRTG-374)
- 포스트 상세 조회 시 세션 검사 해제
- 세션 여부를 따로 확인해, 세션이 있는 경우 찜 여부를 가져오고, 세션이 없는 경우 liked는 false로 고정, count만 가져온다.
> 포스트 상세 조회 시 세션 검사 해제

- .travis.yml
- scripts/deploy.sh
Grtg 359 setting production server
배포 스크립트 수정
- 코드디플로이 그룹명 수정
- 배포 스크립트 상에서 코드디플로이 그룹명을 가져와서 서버 동작시키도록 변경
> chore: Update deploy.sh to set active profile

- api/build.gradle
- api/src/main/resources/application-prod.yml
프로덕션 서버를 위한 환경설정 파일 누락 해결
- application-prod.yml 추가
> 프로덕션 서버를 위한 환경설정 파일 누락 해결

- api/build.gradle
- api/src/main/resources/application-prod.yml
> release v0.6.1

- api/src/main/java/grooteogi/utils/OauthClient.java
- api/src/main/resources/application.yml
OAuth 사용 시 redirect_url을 실행하고 있는 백엔드 url 로 연결
> fix: Change oauth redirect url to environment

- api/build.gradle
- api/src/main/java/grooteogi/config/UserInterceptor.java
- api/src/main/java/grooteogi/controller/AuthController.java
- api/src/main/java/grooteogi/service/AuthService.java
- api/src/main/java/grooteogi/utils/JwtProvider.java
- api/src/main/java/grooteogi/utils/OauthClient.java
- api/src/main/resources/application.yml
- Google, Kakao OAuth 문제 해결
- jwt 빈 문자열로 올 경우 access_token 재발급으로 문제 해결
> OAuth 문제 해결 및 jwt 빈 문자열 처리

- api/src/main/java/grooteogi/dto/PostDto.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
검색, 찜한 포스트, 내가 작성한 포스트 response에 해시태그 미포함 오류 해결
제가 로직을 잘못 짰어요... 그래서 수정했습니다..
> 해시태그 미포함 Response 로직 수정

- api/src/main/java/grooteogi/controller/PostController.java
[GRTG-391](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-391&issueLimit=100)
Decode 기능 추가
> 포스트 검색 시, 한글 값 Decode

- api/src/main/resources/application-prod.yml
기존 30분으로 설정되어 있던 access_token의 시간을 1시간으로 증가
> JWT access_token 유효시간 증가

- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/utils/JwtProvider.java
hotfix
토큰이 없는 경우 예외처리 추가
`NOT_FOUND_TOKEN_EXCEPTION` 추가
> feat: Add not found token exception

- api/src/main/java/grooteogi/repository/PostRepository.java
- api/src/main/java/grooteogi/service/ReservationService.java
[GRTG-393](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-393&issueLimit=100)
날짜 계산에서 틀려서 오류 발생
> 예약 생성 시, 오류 해결

- api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
- api/src/main/java/grooteogi/service/UserService.java
[GRTG-392](https://babiyak.atlassian.net/browse/GRTG-392)
오류 메세지 수정
> 비밀번호 중복 오류 메세지 수정

- api/src/main/java/grooteogi/mapper/PostMapper.java
- api/src/main/java/grooteogi/service/PostService.java
[GRTG-395](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-395&issueLimit=100)
포스트 수정 시, 스케쥴도 함께 수정 되도록 로직 수정
스케쥴 조회 시, 이미 예약된 스케쥴은 보여지지 않도록 수정
> 포스트 수정 오류 해결 및 스케쥴 조회 로직 수정

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/service/PostService.java
[GRTG-397]포스트 like 시 return response 추가
포스트 like할 때 response로 liked와 count 리턴해주도록 수정
[GRTG-397]: https://babiyak.atlassian.net/browse/GRTG-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat: add like response

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/service/PostService.java
Grtg 399 포스트 지역 필터링 수정
지역 필터링 수정
page count 처리 필요
> Grtg 399 포스트 지역 필터링 수정

- api/src/main/java/grooteogi/controller/AuthController.java
> OAuth redirect URL 변경

- api/src/main/java/grooteogi/service/AuthService.java
OAuth 를 이용한 회원가입 시 userInfo 오류 해결
> OAuth 를 이용한 회원가입 시 userInfo 오류 해결

- api/src/main/java/grooteogi/dto/HashtagDto.java
- api/src/main/java/grooteogi/mapper/HashtagMapper.java
- api/src/test/java/grooteogi/HashtagDocumentationTests.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
> 해시태그 response 수정

- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-local.yml
- api/src/main/resources/application-prod.yml
fix: fix for application interceptor
> fix: fix for application interceptor

- api/src/main/java/grooteogi/service/PostService.java
> 포스트 상세 가져오기 수정

- api/src/main/java/grooteogi/controller/PostController.java
- api/src/main/java/grooteogi/service/PostService.java
- api/src/test/java/grooteogi/PostDocumentationTests.java
> fix: fix for search method

- api/src/main/java/grooteogi/controller/ReservationController.java
- api/src/main/java/grooteogi/service/ReservationService.java
- api/src/test/java/grooteogi/ReservationDocumentationTests.java
> 비밀번호 변경 시, 유저 인포 업데이트

- api/build.gradle
> chore: Update version to 1.0.0
