grooteogi/backend

api/src/main/java/grooteogi/controller/HashtagController.java, api/src/main/java/grooteogi/controller/UserController.java, api/src/main/java/grooteogi/controller/UserHashtagController.java, api/src/main/java/grooteogi/dto/response/BasicResponse.java, api/src/main/java/grooteogi/service/UserService.java
update basic_response and maintain user api
-  BasicResponse에서 status를 HttpStatus.OK로 지정
-  더 이상 builder로 값 대입하지 않아도 됨
- get_user 메서드에서 받는 잘못 지정된 path variable 수정
- delete_user 메서드 구현
- patch_user 메서드 삭제
=> update basic_response and maintain user api

api/src/main/java/grooteogi/controller/UserController.java, api/src/main/java/grooteogi/exception/ApiExceptionEnum.java, api/src/main/java/grooteogi/repository/UserRepository.java, api/src/main/java/grooteogi/service/UserService.java
로그인 시 token을 json이 아닌 header에 담아서 전달
- ResponseEntity 전송 시 header와 함께 전달
- 로그인 시 return null 삭제
- ReponseEntity builder()시에는 header가 들어가지 않아 new를 이용
- 추후 확인 후 수정이 필요할 수도 있음
=> Return headers including token when user login

api/src/main/java/grooteogi/utils/JwtProvider.java, api/src/main/java/grooteogi/utils/OauthClient.java
kakao와 google의 oauth router 분리
- OAuth kakao redirect uri 변경
- 카카오 간편 로그인 시 허용 IP가 제한되기 때문에 간편 로그인 테스트 전 말해야 한다.
=> Deal with errors when login using kakao

api/src/main/java/grooteogi/controller/UserHashtagController.java, api/src/main/java/grooteogi/domain/UserHashtag.java, api/src/main/java/grooteogi/dto/UserHashtagDto.java, api/src/main/java/grooteogi/exception/ApiExceptionEnum.java, api/src/main/java/grooteogi/service/HashtagService.java, api/src/main/java/grooteogi/service/UserHashtagService.java
[FEAT] Create modify userHashtag API
유저 프로필 내 해시태그 수정
해시태그 관련 예외처리 추가
- 기존 유저 해시태그 List와 입력받은 해시태그 List 비교
- 추가된 해시태그에 대한 count 증가, 삭제된 해시태그에 대한 count 감소
- POST API와 PUT API에서 존재하지 않는 해시태그가 들어왔을 때 
HASHTAG_NOT_FOUND_EXCEPTION 예외 발생
- UserHashtag 도메인에서 Hashtag Column Annotation @JsonManagedReference로 변경 (API response에서 해시태그 상세 조회 가능) 
- UserHashtag 서비스에서 Get, Post, Put, Delete 순으로 메소드 위치 변경
- UserhastagDto에서 hashtagId -> hashtagIds로 변경
- ApiExceptionEnum에 HASHTAG_NOT_FOUND_EXCEPTION 추가
전에 PR 했던 게 몇 개 겹치는 것 같은데 이번 PR 내용 확인해주시고 저번 거는 무시해주세요!
=> create modify user hashtag api

api/src/main/java/grooteogi/config/AwsS3Config.java, api/src/main/resources/application.yml
#64 [BUG] SignatureDoesNotMatch in AwsS3Config
`AwsS3Config`에서 환경변수로 설정한 엑세스키와 시크릿키를 불러오지 못하는 문제
- `configuration` 어노테이션  `AwsS3Config`에 추가
- AwsS3Config에서 `AWS_ACCESS_KEY`와 `AWS_SECRET_KEY`를 직접 불러오도록 수정
=> Fix: signature does not match in aws s3 config

api/src/main/java/grooteogi/controller/ReservationController.java, api/src/main/java/grooteogi/domain/Reservation.java, api/src/main/java/grooteogi/dto/ReservationRes.java, api/src/main/java/grooteogi/repository/PostRepository.java, api/src/main/java/grooteogi/repository/ReservationRepository.java, api/src/main/java/grooteogi/service/ReservationService.java
#78 reservation api 중 get method 수정
참가자/주최자에 따른 다른 url로 get 요청 처리
- 참가자 "reservation/apply"
- 주최자 "reservation/post" 
ReservationController getPostReservation()
- 주최자의 예약 조회 시, 주최자 id를 param으로 받지 않고 session에서 찾는 로직으로 변경
ReservationController getUserReservation()
- 참가자의 예약 조회 시, 참가자 id를 param으로 받지 않고 session에서 찾는 로직으로 변경
ResevationRes DTO 생성
- 피그마에서 사용하는 데이터만을 담은 DTO 클래스 생성
ReservationService 내부 getTags()
- post의 해시태그 이름만 String[] 타입으로 반환하는 함수 정의
ReservationRepository findPostReservation(id)
- query 조건 추가
ReservationService createReservation()
- 함수 내부 로직 수정할 예정입니다. DB에 값은 잘 들어가요.
=> FIX get reservation

api/src/docs/asciidoc/api.adoc, api/src/main/java/grooteogi/controller/PostController.java, api/src/main/java/grooteogi/controller/ReservationController.java, api/src/main/java/grooteogi/domain/Hashtag.java, api/src/main/java/grooteogi/domain/Heart.java, api/src/main/java/grooteogi/domain/Post.java, api/src/main/java/grooteogi/domain/PostHashtag.java, api/src/main/java/grooteogi/domain/Reservation.java, api/src/main/java/grooteogi/domain/Review.java, api/src/main/java/grooteogi/domain/Schedule.java, api/src/main/java/grooteogi/domain/User.java, api/src/main/java/grooteogi/domain/UserHashtag.java, api/src/main/java/grooteogi/domain/UserInfo.java, api/src/main/java/grooteogi/dto/PostDto.java, api/src/main/java/grooteogi/dto/ReservationDto.java, api/src/main/java/grooteogi/dto/ScheduleDto.java, api/src/main/java/grooteogi/mapper/DateMapper.java, api/src/main/java/grooteogi/mapper/PostMapper.java, api/src/main/java/grooteogi/mapper/ReservationMapper.java, api/src/main/java/grooteogi/mapper/ScheduleMapper.java, api/src/main/java/grooteogi/service/PostService.java, api/src/main/java/grooteogi/service/ReservationService.java, api/src/test/java/grooteogi/ApiDocumentUtils.java, api/src/test/java/grooteogi/PostDocumentationTests.java, api/src/test/java/grooteogi/ReservationDocumentationTests.java
1. Schedule 도메인에서 date, startTime, endTime 타입 변경
2. ReservationDto.Resonse 변경 X
3. 모든 도메인에 아래 어노테이션 추가
``` bash
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Domain { 
....
}
```
4. Post와 PostDto 간의 변수명 동일하게 변경 ( imageUrl )
5. PostMapper로 로직 수정
6. Schedule <> ScheduleDto 간의 date, time 충돌 오류 해결
7. PostDto.Response 임의로 세팅
Schedule
- date : String -> Date
- startTime : String -> Time
- endTime : String -> Time
ReservationMapper
toResponse()에서 @Mapping 조건 추가
``` bash
@Mapping(target = "date", dateFormat = "yyyy-MM-dd")
@Mapping(target = "startTime", dateFormat = "HH:mm")
@Mapping(target = "endTime", dateFormat = "HH:mm")
@Mapping(source = "post.imageUrl", target = "imageUrl")
ReservationDto.Response toResponseDto(Reservation reservation, Post post, Schedule schedule);
``` …
=> refactor: Change date and time type in schedule

.travis.yml
GRTG-279-deploy-project-buildfile-to-s3
main 브랜치에서만 배포되도록 되어 있는 설정을 모든 브랜치를 허용하게 수정
-> develop에 머지 시 배포될 수 있도록 변경
=> fix: Allow s3 deploy on all branches

api/src/main/java/grooteogi/config/RedisConfig.java
GRTG-283-resolve-deploy-error
- RedisConfig 추가
- ERR unknown command `CONFIG`, with args beginning with: `GET`, `notify-keyspace-events` 에러 해결
=> chore: Add redis config to resolve redis error

api/src/main/java/grooteogi/config/RedisConfig.java
GRTG-283-resolve-deploy-error
`@Configuration` 추가
=> fix: Add configuration annotation to redis config

api/src/main/java/grooteogi/config/RedisConfig.java
배포 환경에서 사용하는 elastiCache에서 발생한 오류 해결
- Redis cluster 설정 추가
- 로컬 환경인 경우 미적용
=> chore: Add redis cluster config on deployment

api/src/test/java/grooteogi/HashtagDocumentationTests.java
- 해시태그 조회
- 해시태그 생성
- 해시태그 검색
테스트 코드 형식만 작성
=> 해시태그 컨트롤러 api 테스트

api/src/main/java/grooteogi/service/AwsS3Service.java
Refactor with deleteImage in S3Service
- AwsS3Service 내 deleteImage에서 기존에는 이미지의 직접적인 키 ex)image.png 만 받게 했으나
저장되는 imageUrl이 객체 링크 ex)https://dev-grtg-bucket.s3.ap-northeast-2.amazonaws.com/image.png 인점을 고려하여 객체 링크를 받고 직접적인 키는 split 함수를 통하여 분리시키고, 그 값을 받아 delete하게 함
- deleteImage 메소드 내 String imgUrl = fileName.split("/")[3]; 추가
=> refactor: Refactor with deleteImage in S3Service

api/src/main/java/grooteogi/dto/ReservationDto.java, api/src/main/java/grooteogi/mapper/ReservationMapper.java, api/src/main/java/grooteogi/service/ReservationService.java, api/src/test/java/grooteogi/ReservationDocumentationTests.java
- 예약 Response DTO 필드 추가 ( 참가자 닉네임, 예약 시  남기는 말 )
- 예약 Mapper 매핑 조건 추가
- 예약 서비스에서 DetailResponse 리턴하는 모든 get 요청 로직 수정 
- DTO 변경에 따른 예약 테스트 코드 문서화 시, fields 추가
```` bash
{
"status": 200,
"message": "get reservation success",
"data": {
"title": "test-title26",
"date": "2022-05-29",
"startTime": "14:00:00",
"endTime": "15:00:00",
"region": "SEODAEMUN",
"place": "우물카페",
"postId": 1,
"imageUrl": "",
"isCanceled": false,
"hostPhone": "01098765432",
"applyPhone": "01012345678",
"applyNickname": "groot-2",
"text": "dto 수정 후 테스트"
}
}
````
포스트맨으로 테스트 후에 보여지는 결과값
=> 예약 Response DTO 변경에 따른 리펙토링

api/src/main/java/grooteogi/controller/AuthController.java, api/src/main/java/grooteogi/dto/AuthDto.java, api/src/main/java/grooteogi/exception/ApiExceptionEnum.java, api/src/main/java/grooteogi/service/AuthService.java
- DTO에 존재하는 모든 이메일 형식 체크 방식 통일화
- 회원 탈퇴 시, Request Param 삭제 및 세션에서 Id 찾아오는 방식으로 수정
- 이메일 인증 코드 확인 시, time-out 오류 추가
=> Auth DTO 이메일 어노테이션 수정 및 회원 탈퇴 request param 삭제

api/src/main/java/grooteogi/mapper/HashtagMapper.java, api/src/main/java/grooteogi/service/HashtagService.java
[문제 상황]
Request Param이 없거나 `""` 인 경우, `""` 인 hashtag가 생성.
[변경된 로직]
Request Param이 없거나 `""` 인 경우, 가장 많이 사용된 해시태그를 반환
[매퍼 수정]
해시태그 생성 시, 매퍼에 넘기는 파라미터를 Request 객체가 아닌, string 으로 변경
해시태그 검색에서 검색어에 해당하는 해시태그가 존재하지 않는다면,  새로 생성할 때 사용하기 위함
=> 해시태그 검색 로직 수정

api/src/main/java/grooteogi/service/PostService.java
response에 해시태그 set하는 코드 누락으로 발생한 이슈 해결
```` bash
public PostDto.Response getPostResponse(Integer postId, String jwt) {
Optional<Post> post = postRepository.findById(postId);
if (post.isEmpty()) {
throw new ApiException(ApiExceptionEnum.POST_NOT_FOUND_EXCEPTION);
}
//조회수 증가
post.get().setViews(post.get().getViews() + 1);
Post updatePost = postRepository.save(post.get());
PostDto.Response result = PostMapper.INSTANCE.toDetailResponse(updatePost);
result.setHashtags(getPostHashtags(updatePost.getPostHashtags()));
User user = post.get().getUser();
result.setMentor(PostMapper.INSTANCE.toUserResponse(user, user.getUserInfo()));
List<Heart> hearts = heartRepository.findByPost(post.get());
if (jwt != null) {
jwt = jwtProvider.extractToken(jwt);
jwtProvider.isUsable(jwt);
Session session = …
```
=> 포스트 Detail response 로직 수정

api/src/main/java/grooteogi/dto/UserDto.java, api/src/main/java/grooteogi/exception/ApiExceptionEnum.java, api/src/main/java/grooteogi/service/UserService.java, api/src/test/java/grooteogi/UserDocumentationTests.java
[GRTG-380](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-380&issueLimit=100)
```` bash
public void modifyUserPw(Integer userId, UserDto.PasswordRequest request) {
Optional<User> user = userRepository.findById(userId);
user.orElseThrow(() -> new ApiException(ApiExceptionEnum.USER_NOT_FOUND_EXCEPTION));
if (!passwordEncoder.matches(request.getCurrentPassword(), user.get().getPassword())) {
throw new ApiException(ApiExceptionEnum.PASSWORD_DISCORD_EXCEPTION);
}
if (request.getCurrentPassword().equals(request.getNewPassword())) {
throw new ApiException(ApiExceptionEnum.DUPLICATION_VALUE_EXCEPTION);
}
validator.confirmPasswordVerification(request.getNewPassword());
user.get().setPassword(passwordEncoder.encode(request.getNewPassword() …
```
=> 비밀번호 변경 Request DTO 변경에 따른 로직 수정

api/src/main/java/grooteogi/dto/PostDto.java, api/src/main/java/grooteogi/service/PostService.java
feat: add isAuthor in postDto and set about that in postService
- post detail에서 isAuthor 확인할 수 있게 postDto response에 attribute 추가
- postservice에서 멘토 id가 session id와 같다면 isAuthor true, 아닐 경우 false
=> feat: add isAuthor in postDto and set about that in postService

api/src/main/java/grooteogi/mapper/UserMapper.java, api/src/main/java/grooteogi/service/AuthService.java, api/src/main/java/grooteogi/service/UserService.java
[GRTG-383](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-383&issueLimit=100)
유저 닉네임 변경 시, mapper에서 parameter 누락으로 인해 변경이 안되는 오류 발생
```` bash
public void modifyUserProfile(Integer userId, ProfileDto.Request request) {
Optional<User> user = userRepository.findById(userId);
user.orElseThrow(() -> new ApiException(ApiExceptionEnum.USER_NOT_FOUND_EXCEPTION));
if (!user.get().getNickname().equals(request.getNickname())
&& userRepository.existsByNickname(request.getNickname())) {
throw new ApiException(ApiExceptionEnum.DUPLICATION_VALUE_EXCEPTION);
}
UserInfo userInfo = userInfoRepository.save(UserInfoMapper.INSTANCE.toEntity(request));
User modifiedUser = UserMapper.INSTANCE.toModify(user.get(), request.getNickname(), userInfo); …
```
=> 유저 닉네임 변경 로직 오류 해결

api/src/main/java/grooteogi/enums/RegionType.java, api/src/main/java/grooteogi/mapper/PostMapper.java
[GRTG-384](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-384&issueLimit=100)
문제 상황 : Region 값이 영어로 return 된다.
원인 : ReginType `Enum to string` 시, `toString()` 메소드 overriding 문제
해결 : String으로 변경해주는 함수를 enum class에 생성
```` bash
...
GANGBUK("강북구"),
DOBONG("도봉구")
;
private final String label;
RegionType(String label) {
this.label = label;
}
public String getLabel() {
return this.label;
}
````
위의 enum class에서 `getLabel()` 함수 생성
```` bash
default String asStringRegion(RegionType type) {
return type != null ? type.getLabel() : null;
}
````
위의 PostMapper.java에서 `asStringRegion()` 리턴 시, type.toString() -> type.getLabel() 로 변경
아래는 포스트맨으로 테스트
=> 지역 Enum to String 변경 함수 생성 및 적용

api/src/main/java/grooteogi/controller/ReservationController.java, api/src/main/java/grooteogi/dto/ReservationDto.java, api/src/main/java/grooteogi/service/ReservationService.java, api/src/test/java/grooteogi/ReservationDocumentationTests.java
[GRTG-394] sms 전송 시 인증 코드 리턴 수정
response 삭제하고 service에서 void로 바꿈!
[GRTG-394]: https://babiyak.atlassian.net/browse/GRTG-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix: remove sms response

api/src/main/java/grooteogi/dto/ReservationDto.java, api/src/main/java/grooteogi/mapper/ReservationMapper.java, api/src/main/java/grooteogi/service/ReservationService.java, api/src/test/java/grooteogi/ReservationDocumentationTests.java
[GRTG-401](https://babiyak.atlassian.net/jira/software/c/projects/GRTG/boards/1/backlog?view=detail&selectedIssue=GRTG-401&issueLimit=100)
호스트 유저 연락처 검증 삭제
호스트 유저 연락처 response 에서 삭제
=> 예약 조회 시, 호스트 유저 연락처 검증 로직 삭제
